language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO="django>=1.11.0,<2.0"
  - DJANGO="django>=2.0,<2.1"

install:
  - travis_retry pip install -q coveralls  # installs coverage
  - travis_retry pip install $DJANGO
  - pip install -e .

script:
  - coverage run --source=p3p runtests.py

after_success:
  - coveralls --verbose
